[2023-12-13T04:47:21.964+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: namegender_v5.load scheduled__2023-12-12T02:00:00+00:00 [queued]>
[2023-12-13T04:47:21.978+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: namegender_v5.load scheduled__2023-12-12T02:00:00+00:00 [queued]>
[2023-12-13T04:47:21.978+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-12-13T04:47:21.978+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2023-12-13T04:47:21.978+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-12-13T04:47:22.001+0000] {taskinstance.py:1300} INFO - Executing <Task(_PythonDecoratedOperator): load> on 2023-12-12 02:00:00+00:00
[2023-12-13T04:47:22.006+0000] {standard_task_runner.py:55} INFO - Started process 4273 to run task
[2023-12-13T04:47:22.008+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'namegender_v5', 'load', 'scheduled__2023-12-12T02:00:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/NameGenderCSVtoRedshift_v5.py', '--cfg-path', '/tmp/tmpttru66uj']
[2023-12-13T04:47:22.008+0000] {standard_task_runner.py:83} INFO - Job 7: Subtask load
[2023-12-13T04:47:22.073+0000] {task_command.py:388} INFO - Running <TaskInstance: namegender_v5.load scheduled__2023-12-12T02:00:00+00:00 [running]> on host 4c47452e42c3
[2023-12-13T04:47:22.178+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=namegender_v5
AIRFLOW_CTX_TASK_ID=load
AIRFLOW_CTX_EXECUTION_DATE=2023-12-12T02:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-12-12T02:00:00+00:00
[2023-12-13T04:47:22.179+0000] {NameGenderCSVtoRedshift_v5.py:40} INFO - load started
[2023-12-13T04:47:22.190+0000] {base.py:73} INFO - Using connection ID 'redshift_dev_db' for task execution.
[2023-12-13T04:47:22.372+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/dags/NameGenderCSVtoRedshift_v5.py", line 52, in load
    cur.execute(f"DELETE FROM {schema}.name_gender;")
psycopg2.errors.InsufficientPrivilege: permission denied for schema keeyong


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 217, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/NameGenderCSVtoRedshift_v5.py", line 61, in load
    except (Exception, psycopg2.DatabaseError) as error:
NameError: name 'psycopg2' is not defined
[2023-12-13T04:47:22.386+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=namegender_v5, task_id=load, execution_date=20231212T020000, start_date=20231213T044721, end_date=20231213T044722
[2023-12-13T04:47:22.406+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 7 for task load (name 'psycopg2' is not defined; 4273)
[2023-12-13T04:47:22.426+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-12-13T04:47:22.445+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
