[2023-12-16T12:31:37.631+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: UpdateSymbol.load manual__2023-12-16T12:31:28.093109+00:00 [queued]>
[2023-12-16T12:31:37.669+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: UpdateSymbol.load manual__2023-12-16T12:31:28.093109+00:00 [queued]>
[2023-12-16T12:31:37.670+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-12-16T12:31:37.670+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-12-16T12:31:37.670+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-12-16T12:31:37.751+0000] {taskinstance.py:1300} INFO - Executing <Task(_PythonDecoratedOperator): load> on 2023-12-16 12:31:28.093109+00:00
[2023-12-16T12:31:37.770+0000] {standard_task_runner.py:55} INFO - Started process 3238 to run task
[2023-12-16T12:31:37.783+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'UpdateSymbol', 'load', 'manual__2023-12-16T12:31:28.093109+00:00', '--job-id', '54', '--raw', '--subdir', 'DAGS_FOLDER/UpdateSymbol.py', '--cfg-path', '/tmp/tmpvvh3o1c3']
[2023-12-16T12:31:37.784+0000] {standard_task_runner.py:83} INFO - Job 54: Subtask load
[2023-12-16T12:31:39.460+0000] {task_command.py:388} INFO - Running <TaskInstance: UpdateSymbol.load manual__2023-12-16T12:31:28.093109+00:00 [running]> on host 071ea05dffbb
[2023-12-16T12:31:39.587+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=UpdateSymbol
AIRFLOW_CTX_TASK_ID=load
AIRFLOW_CTX_EXECUTION_DATE=2023-12-16T12:31:28.093109+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-12-16T12:31:28.093109+00:00
[2023-12-16T12:31:39.588+0000] {UpdateSymbol.py:34} INFO - load started
[2023-12-16T12:31:39.596+0000] {base.py:73} INFO - Using connection ID 'redshift_dev_db' for task execution.
[2023-12-16T12:31:40.617+0000] {logging_mixin.py:137} INFO - duplicate key violates unique constraint "pg_class_relname_nsp_index" (possibly caused by concurrent transaction conflict)
[2023-12-16T12:31:40.627+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 217, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/UpdateSymbol.py", line 47, in load
    );""")
psycopg2.errors.UniqueViolation: duplicate key violates unique constraint "pg_class_relname_nsp_index" (possibly caused by concurrent transaction conflict)

[2023-12-16T12:31:40.638+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=UpdateSymbol, task_id=load, execution_date=20231216T123128, start_date=20231216T123137, end_date=20231216T123140
[2023-12-16T12:31:40.673+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 54 for task load (duplicate key violates unique constraint "pg_class_relname_nsp_index" (possibly caused by concurrent transaction conflict)
; 3238)
[2023-12-16T12:31:40.705+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-12-16T12:31:40.727+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
